django-root/dashboard/urls.py
from authtools.views import LogoutView
from decorator_include import decorator_include
from django.conf.urls import url
from stronghold.decorators import public

from dashboard.views.assessment import CourseAssessmentView
from dashboard.views.communication import CourseCommunicationView
from dashboard.views.content import CourseContentView
from dashboard.views.content import ResourcePageView
from dashboard.views.courses import CourseListView
from dashboard.views.dashboard import CourseDashboardView
from dashboard.views.events import CourseRepeatingEventCreateView
from dashboard.views.events import CourseRepeatingEventDeleteView
from dashboard.views.events import CourseRepeatingEventListView
from dashboard.views.events import CourseRepeatingEventUpdateView
from dashboard.views.events import CourseSingleEventCreateView
from dashboard.views.events import CourseSingleEventDeleteView
from dashboard.views.events import CourseSingleEventListView
from dashboard.views.events import CourseSingleEventUpdateView
from dashboard.views.events import CourseSubmissionEventCreateView
from dashboard.views.events import CourseSubmissionEventDeleteView
from dashboard.views.events import CourseSubmissionEventListView
from dashboard.views.events import CourseSubmissionEventUpdateView
from dashboard.views.students import StudentDetailView
from dashboard.views.students import StudentsView
from dashboard.views.users import CustomLoginView
from dashboard.views.users import DashboardRedirectView
from django_site.permissions import course_access_url_wrapper


urlpatterns = [
    url(r'^$', DashboardRedirectView.as_view(), name='dashboard_redirect'),
    url(r'^login/', public(CustomLoginView.as_view()), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),

    url(r'^courses/', CourseListView.as_view(), name='course_list'),

    url(r'^(?P<course_id>\d+)/', decorator_include(course_access_url_wrapper, [
        url(r'^course_dashboard/$', CourseDashboardView.as_view(), name='course_dashboard'),
        url(r'^assessment/$', CourseAssessmentView.as_view(), name='course_assessments'),
        url(r'^communication/$', CourseCommunicationView.as_view(), name='course_communications'),
        url(r'^course_content/$', CourseContentView.as_view(), name='course_content'),
        url(r'^students/$', StudentsView.as_view(), name='students'),
        url(r'^student/(?P<pk>\d+)/$', StudentDetailView.as_view(), name='student_detail'),
        url(r'^course_page/(?P<pk>\d+)/$', ResourcePageView.as_view(), name='course_page'),

        # Event management for academic staff
        url(r'^course_repeating_events/$', CourseRepeatingEventListView.as_view(), name='list_course_repeating_events'),
        url(r'^course_repeating_event/$', CourseRepeatingEventCreateView.as_view(), name='add_course_repeating_event'),
        url(r'^course_repeating_event/(?P<pk>\d+)/$', CourseRepeatingEventUpdateView.as_view(), name='edit_course_repeating_event'),
        url(r'^course_repeating_event/(?P<pk>\d+)/delete/$', CourseRepeatingEventDeleteView.as_view(), name='delete_course_repeating_event'),
        url(r'^course_submission_events/$', CourseSubmissionEventListView.as_view(), name='list_course_submission_events'),
        url(r'^course_submission_event/$', CourseSubmissionEventCreateView.as_view(), name='add_course_submission_event'),
        url(r'^course_submission_event/(?P<pk>\d+)/$', CourseSubmissionEventUpdateView.as_view(), name='edit_course_submission_event'),
        url(r'^course_submission_event/(?P<pk>\d+)/delete/$', CourseSubmissionEventDeleteView.as_view(), name='delete_course_submission_event'),
        url(r'^course_single_events/$', CourseSingleEventListView.as_view(), name='list_course_single_events'),
        url(r'^course_single_event/$', CourseSingleEventCreateView.as_view(), name='add_course_single_event'),
        url(r'^course_single_event/(?P<pk>\d+)/$', CourseSingleEventUpdateView.as_view(), name='edit_course_single_event'),
        url(r'^course_single_event/(?P<pk>\d+)/delete/$', CourseSingleEventDeleteView.as_view(), name='delete_course_single_event'),
    ])),
]

django-root/django_site/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('olap.urls', namespace='olap')),
    url(r'^', include('dashboard.urls', namespace='dashboard'))
]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

django-root/olap/urls.py
from decorator_include import decorator_include
from django.conf.urls import url
from stronghold.decorators import public

from django_site.permissions import course_access_url_wrapper
from olap.views.assessment import AssessmentAccessesView
from olap.views.assessment import AssessmentEventsView
from olap.views.assessment import AssessmentGradesView
from olap.views.assessment import AssessmentStudentsView
from olap.views.common import CoursePageVisitsView
from olap.views.common import StudentPageVisitsView
from olap.views.communication import CommunicationAccessesView
from olap.views.communication import CommunicationEventsView
from olap.views.communication import CommunicationPostsView
from olap.views.communication import CommunicationStudentsView
from olap.views.content import ContentAccessesView
from olap.views.content import ContentEventsView
from olap.views.content import ContentStudentsView
from olap.views.content import StudentsNotViewedResourceView
from olap.views.dashboard import PerWeekMetricsView
from olap.views.dashboard import PerWeekPageVisitsView
from olap.views.dashboard import TopAccessedContentView
from olap.views.dashboard import TopAssessmentAccessView
from olap.views.dashboard import TopCommunicationAccessView
from olap.views.dashboard import TopCourseUsersViewSet
from olap.views.importer import CourseImportsApiView
from olap.views.student import StudentAssessmentView
from olap.views.student import StudentCommunicationView
from olap.views.students import StudentsAccessesView
from olap.views.students import StudentsEventsView

urlpatterns = [
    # This endpoint is protected with Token Authentication
    url(r'^course_imports/$', public(CourseImportsApiView.as_view()), name='course_imports'),

    url(r'^(?P<course_id>\d+)/', decorator_include(course_access_url_wrapper, [
        url(r'^assessment_accesses/$', AssessmentAccessesView.as_view(), name='assessment_accesses'),
        url(r'^assessment_grades/$', AssessmentGradesView.as_view(), name='assessment_grades'),
        url(r'^assessment_students/$', AssessmentStudentsView.as_view(), name='assessment_students'),
        url(r'^assessment_events/(?P<event_id>\d+)/$', AssessmentEventsView.as_view(), name='assessment_events'),

        url(r'^communication_accesses/$', CommunicationAccessesView.as_view(), name='communication_accesses'),
        url(r'^communication_posts/$', CommunicationPostsView.as_view(), name='communication_posts'),
        url(r'^communication_students/$', CommunicationStudentsView.as_view(), name='communication_students'),
        url(r'^communication_events/(?P<event_id>\d+)/$', CommunicationEventsView.as_view(), name='communication_events'),

        url(r'^content_accesses/$', ContentAccessesView.as_view(), name='content_accesses'),
        url(r'^content_students/$', ContentStudentsView.as_view(), name='content_students'),
        url(r'^content_events/(?P<event_id>\d+)/$', ContentEventsView.as_view(), name='content_events'),

        url(r'^students_accesses/$', StudentsAccessesView.as_view(), name='students_accesses'),
        url(r'^students_events/(?P<event_id>\d+)/$', StudentsEventsView.as_view(), name='students_events'),

        url(r'^student_assessments/(?P<student_id>\d+)/$', StudentAssessmentView.as_view(), name='student_assessments'),
        url(r'^student_communications/(?P<student_id>\d+)/$', StudentCommunicationView.as_view(), name='student_communications'),

        url(r'^course_page_visits/$', CoursePageVisitsView.as_view(), name='course_page_visits'),
        url(r'^student_page_visits/$', StudentPageVisitsView.as_view(), name='student_page_visits'),

        url(r'^top_assessments/(?:(?P<week_num>\d+)/)?$', TopAssessmentAccessView.as_view(), name='top_assessment'), # optional week
        url(r'^top_communication/(?:(?P<week_num>\d+)/)?$', TopCommunicationAccessView.as_view(), name='top_communication'), # optional week
        url(r'^top_content/(?:(?P<week_num>\d+)/)?$', TopAccessedContentView.as_view(), name='top_content'), # optional week
        url(r'^top_users/$', TopCourseUsersViewSet.as_view(), name='top_users'),

        url(r'^weekly_page_visits/(?P<week_num>\d+)/$', PerWeekPageVisitsView.as_view(), name='per_week_page_visits'),
        url(r'^weekly_metrics/(?P<week_num>\d+)/$', PerWeekMetricsView.as_view(), name='per_week_metrics'),

        url(r'^resource/(?P<resource_id>\d+)/not_viewed_students/$', StudentsNotViewedResourceView.as_view(), name='students_not_viewed_resource'),

    ])),
]

django-root/django_site/templates/base.html
{% extends 'base_unauthorised.html' %}

{% block body %}

  <header class="banner">
    <!-- start: Header -->
    <div class="navbar">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <a class="brand" href="{% url 'dashboard:course_list' %}"><span>Loop - Analytics for Learning Design </span></a>

          <!-- start: Header Menu -->
          <div class="nav-no-collapse header-nav">
            <ul class="nav">
              <!-- start: User Dropdown -->
              <li class="dropdown">
                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                  <i class="glyphicon glyphicon-user white"></i> {{ user.username }}
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li class="dropdown-menu-title">
                    <span>Account Settings</span>
                  </li>
                  <li><a href="{% url 'dashboard:logout' %}"><i class="glyphicon glyphicon-off"></i> Logout</a></li>
                </ul>
              </li>
              <!-- end: User Dropdown -->
            </ul>
          </div>
          <!-- end: Header Menu -->
        </div>
      </div>
    </div>
  </header>
  <!-- end: Header -->

  <main class="main">
    <div class="container-fluid">
    <div class="row main-row">
      <!-- start: Main Menu -->
      <div id="sidebar-left" class="col-sm-3 col-md-2 sidebar">
        {% if request.course_offering %}
          <div class="sidebar__bd">
            <ul class="nav nav-tabs nav-stacked main-menu">
              <li>
                <a href="{% url 'dashboard:course_dashboard' course_id=request.course_offering.id %}">
                  <i class="glyphicon glyphicon-stats"></i> Course Dashboard
                </a>
              </li>
              <li>
                <a href="#access-menu" data-toggle="collapse">
                  <i class="glyphicon glyphicon-list-alt"></i> Course Access
                </a>
                <ul class="collapse" id="access-menu">
                  <li>
                    <a class="submenu" href="{% url 'dashboard:course_content' course_id=request.course_offering.id %}">
                      Content
                    </a>
                  </li>
                  <li>
                    <a class="submenu" href="{% url 'dashboard:course_communications' course_id=request.course_offering.id %}">
                      Communication
                    </a>
                  </li>
                  <li>
                    <a class="submenu" href="{% url 'dashboard:course_assessments' course_id=request.course_offering.id %}">
                      Assessment
                    </a>
                  </li>
                </ul>
              </li>
              <li>
                <a href="{% url 'dashboard:students' course_id=request.course_offering.id %}">
                  <i class="glyphicon glyphicon-user"></i> Students
                </a>
              </li>
              <li>
                <a href="#events-menu" data-toggle="collapse">
                  <i class="glyphicon glyphicon-pencil"></i> Course Events
                </a>
                <ul class="collapse" id="events-menu">
                  <li>
                    <a class="submenu" href="{% url 'dashboard:list_course_repeating_events' course_id=request.course_offering.id %}">
                      Repeating Events
                    </a>
                  </li>
                  <li>
                    <a class="submenu" href="{% url 'dashboard:list_course_submission_events' course_id=request.course_offering.id %}">
                      Submission Events
                    </a>
                  </li>
                  <li>
                    <a class="submenu" href="{% url 'dashboard:list_course_single_events' course_id=request.course_offering.id %}">
                      Single Events
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        {% endif %}
        </div>
      <!-- end: Main Menu -->

      <noscript>
        <div class="alert alert-block span10">
          <h4 class="alert-heading">Warning!</h4>
          <p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
        </div>
      </noscript>

      <!-- start: Content -->
      <div id="content" class="col-sm-9 col-md-10">
        {% block breadcrumb %}
        <!--
          <ul class="breadcrumb">
            <li>
              <i class="icon-home"></i>
              <a href="{% url 'dashboard:course_list' %}">CLoop</a>
              <i class="icon-angle-right"></i>
            </li>
            <li>
              <a href="#">My Courses</a>
            </li>
          </ul>
          -->
        {% endblock %}

        {% block content %}

        {% endblock content %}
      </div><!--/#content.span10-->
      <!-- end: Content -->
    </div><!--/fluid-row-->
  </div><!--/.fluid-container-->
  </main>
  <footer class="content-info">
    <div class="container-fluid">
      <p>
        2016 Loop OLT Project - <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike</a>
      </p>
    </div>
  </footer>

{% endblock body %}

django-root/django_site/templates/base_unauthorised.html
{% load static %}
{% load render_bundle from webpack_loader %}

<!DOCTYPE html>
<html lang="en">
<head>

  <!-- start: Meta -->
  <meta charset="utf-8">
  <title>CLoop Analytics - {% block title %} My Courses {% endblock %}</title>
  <meta name="description" content="Analytics for Learning Design from Popular LMS such as Moodle and Blackboard">
  <meta name="author" content="Closing the Loop - ALTC Grant">
  <meta name="keyword" content="Analytics, Learning Design, Moodle, Blackboard">
  <!-- end: Meta -->

  <!-- start: Mobile Specific -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- end: Mobile Specific -->

  <!-- start: Favicon -->
  <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
  <!-- end: Favicon -->

  <!-- start: CSS -->
  <link href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext,latin-ext" rel="stylesheet" type="text/css">
  {% render_bundle 'main' 'css' %}
  {% block stylesheets%}

  {% endblock stylesheets %}
  <!-- end: CSS -->

{#  <link id="base-style" href="/static/css/style.css" rel="stylesheet">#}
{#  <link id="base-style-responsive" href="/static/css/style-responsive.css" rel="stylesheet">#}
{#  <link rel="stylesheet" href="/static/css/jstree/themes/default/style.min.css" />#}

{#<style>#}
{#  .node {#}
{#    cursor: pointer;#}
{#  }#}
{##}
{#  .overlay{#}
{#      background-color:#EEE;#}
{#  }#}
{##}
{#  .node circle {#}
{#    fill: #fff;#}
{#    stroke: steelblue;#}
{#    stroke-width: 1.5px;#}
{#  }#}
{##}
{#  .node text {#}
{#    font-size:10px;#}
{#    font-family:sans-serif;#}
{#  }#}
{##}
{#  .link {#}
{#    fill: none;#}
{#    stroke: #ccc;#}
{#    stroke-width: 1.5px;#}
{#  }#}
{##}
{#  .additionalParentLink {#}
{#    fill: none;#}
{#    stroke: blue;#}
{#    stroke-width: 1.5px;#}
{#  }#}
{##}
{#  .templink {#}
{#    fill: none;#}
{#    stroke: red;#}
{#    stroke-width: 3px;#}
{#  }#}
{##}
{#  .ghostCircle.show{#}
{#      display:block;#}
{#  }#}
{##}
{#  .ghostCircle, .activeDrag .ghostCircle{#}
{#       display: none;#}
{#  }#}
{#</style>#}
{##}
{#  <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->#}
{#  <!--[if lt IE 9]>#}
{#      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>#}
{#    <link id="ie-style" href="css/ie.css" rel="stylesheet">#}
{#  <![endif]-->#}
{##}
{#  <!--[if IE 9]>#}
{#    <link id="ie9style" href="css/ie9.css" rel="stylesheet">#}
{#  <![endif]-->#}
</head>

<body>
  <div id="{% block page_id %}{% endblock page_id %}" class="page {% block container_class %}{% endblock container_class %}">
    {% block body %}

    {% endblock body %}
  </div>
  <script>
    window.__APP_CONTEXT__ = JSON.parse('{{ CONSTANTS | escapejs }}');
  </script>

  {% render_bundle 'main' 'js' %}
  {% block javascript %}

  {% endblock javascript %}
</body>

</html>