django-root/dashboard/urls.py
from authtools.views import LogoutView
from decorator_include import decorator_include
from django.conf.urls import url
from stronghold.decorators import public

from dashboard.views.assessment import CourseAssessmentView
from dashboard.views.communication import CourseCommunicationView
from dashboard.views.content import CourseContentView
from dashboard.views.content import ResourcePageView
from dashboard.views.courses import CourseListView
from dashboard.views.dashboard import CourseDashboardView
from dashboard.views.events import CourseRepeatingEventCreateView
from dashboard.views.events import CourseRepeatingEventDeleteView
from dashboard.views.events import CourseRepeatingEventListView
from dashboard.views.events import CourseRepeatingEventUpdateView
from dashboard.views.events import CourseSingleEventCreateView
from dashboard.views.events import CourseSingleEventDeleteView
from dashboard.views.events import CourseSingleEventListView
from dashboard.views.events import CourseSingleEventUpdateView
from dashboard.views.events import CourseSubmissionEventCreateView
from dashboard.views.events import CourseSubmissionEventDeleteView
from dashboard.views.events import CourseSubmissionEventListView
from dashboard.views.events import CourseSubmissionEventUpdateView
from dashboard.views.students import StudentDetailView
from dashboard.views.students import StudentsView
from dashboard.views.users import CustomLoginView
from dashboard.views.users import DashboardRedirectView
from django_site.permissions import course_access_url_wrapper


urlpatterns = [
    url(r'^$', DashboardRedirectView.as_view(), name='dashboard_redirect'),
    url(r'^login/', public(CustomLoginView.as_view()), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),

    url(r'^courses/', CourseListView.as_view(), name='course_list'),

    url(r'^(?P<course_id>\d+)/', decorator_include(course_access_url_wrapper, [
        url(r'^course_dashboard/$', CourseDashboardView.as_view(), name='course_dashboard'),
        url(r'^assessment/$', CourseAssessmentView.as_view(), name='course_assessments'),
        url(r'^communication/$', CourseCommunicationView.as_view(), name='course_communications'),
        url(r'^course_content/$', CourseContentView.as_view(), name='course_content'),
        url(r'^students/$', StudentsView.as_view(), name='students'),
        url(r'^student/(?P<pk>\d+)/$', StudentDetailView.as_view(), name='student_detail'),
        url(r'^course_page/(?P<pk>\d+)/$', ResourcePageView.as_view(), name='course_page'),

        # Event management for academic staff
        url(r'^course_repeating_events/$', CourseRepeatingEventListView.as_view(), name='list_course_repeating_events'),
        url(r'^course_repeating_event/$', CourseRepeatingEventCreateView.as_view(), name='add_course_repeating_event'),
        url(r'^course_repeating_event/(?P<pk>\d+)/$', CourseRepeatingEventUpdateView.as_view(), name='edit_course_repeating_event'),
        url(r'^course_repeating_event/(?P<pk>\d+)/delete/$', CourseRepeatingEventDeleteView.as_view(), name='delete_course_repeating_event'),
        url(r'^course_submission_events/$', CourseSubmissionEventListView.as_view(), name='list_course_submission_events'),
        url(r'^course_submission_event/$', CourseSubmissionEventCreateView.as_view(), name='add_course_submission_event'),
        url(r'^course_submission_event/(?P<pk>\d+)/$', CourseSubmissionEventUpdateView.as_view(), name='edit_course_submission_event'),
        url(r'^course_submission_event/(?P<pk>\d+)/delete/$', CourseSubmissionEventDeleteView.as_view(), name='delete_course_submission_event'),
        url(r'^course_single_events/$', CourseSingleEventListView.as_view(), name='list_course_single_events'),
        url(r'^course_single_event/$', CourseSingleEventCreateView.as_view(), name='add_course_single_event'),
        url(r'^course_single_event/(?P<pk>\d+)/$', CourseSingleEventUpdateView.as_view(), name='edit_course_single_event'),
        url(r'^course_single_event/(?P<pk>\d+)/delete/$', CourseSingleEventDeleteView.as_view(), name='delete_course_single_event'),
    ])),
]

django-root/django_site/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('olap.urls', namespace='olap')),
    url(r'^', include('dashboard.urls', namespace='dashboard'))
]

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

django-root/olap/urls.py
from decorator_include import decorator_include
from django.conf.urls import url
from stronghold.decorators import public

from django_site.permissions import course_access_url_wrapper
from olap.views.assessment import AssessmentAccessesView
from olap.views.assessment import AssessmentEventsView
from olap.views.assessment import AssessmentGradesView
from olap.views.assessment import AssessmentStudentsView
from olap.views.common import CoursePageVisitsView
from olap.views.common import StudentPageVisitsView
from olap.views.communication import CommunicationAccessesView
from olap.views.communication import CommunicationEventsView
from olap.views.communication import CommunicationPostsView
from olap.views.communication import CommunicationStudentsView
from olap.views.content import ContentAccessesView
from olap.views.content import ContentEventsView
from olap.views.content import ContentStudentsView
from olap.views.content import StudentsNotViewedResourceView
from olap.views.dashboard import PerWeekMetricsView
from olap.views.dashboard import PerWeekPageVisitsView
from olap.views.dashboard import TopAccessedContentView
from olap.views.dashboard import TopAssessmentAccessView
from olap.views.dashboard import TopCommunicationAccessView
from olap.views.dashboard import TopCourseUsersViewSet
from olap.views.importer import CourseImportsApiView
from olap.views.student import StudentAssessmentView
from olap.views.student import StudentCommunicationView
from olap.views.students import StudentsAccessesView
from olap.views.students import StudentsEventsView

urlpatterns = [
    # This endpoint is protected with Token Authentication
    url(r'^course_imports/$', public(CourseImportsApiView.as_view()), name='course_imports'),

    url(r'^(?P<course_id>\d+)/', decorator_include(course_access_url_wrapper, [
        url(r'^assessment_accesses/$', AssessmentAccessesView.as_view(), name='assessment_accesses'),
        url(r'^assessment_grades/$', AssessmentGradesView.as_view(), name='assessment_grades'),
        url(r'^assessment_students/$', AssessmentStudentsView.as_view(), name='assessment_students'),
        url(r'^assessment_events/(?P<event_id>\d+)/$', AssessmentEventsView.as_view(), name='assessment_events'),

        url(r'^communication_accesses/$', CommunicationAccessesView.as_view(), name='communication_accesses'),
        url(r'^communication_posts/$', CommunicationPostsView.as_view(), name='communication_posts'),
        url(r'^communication_students/$', CommunicationStudentsView.as_view(), name='communication_students'),
        url(r'^communication_events/(?P<event_id>\d+)/$', CommunicationEventsView.as_view(), name='communication_events'),

        url(r'^content_accesses/$', ContentAccessesView.as_view(), name='content_accesses'),
        url(r'^content_students/$', ContentStudentsView.as_view(), name='content_students'),
        url(r'^content_events/(?P<event_id>\d+)/$', ContentEventsView.as_view(), name='content_events'),

        url(r'^students_accesses/$', StudentsAccessesView.as_view(), name='students_accesses'),
        url(r'^students_events/(?P<event_id>\d+)/$', StudentsEventsView.as_view(), name='students_events'),

        url(r'^student_assessments/(?P<student_id>\d+)/$', StudentAssessmentView.as_view(), name='student_assessments'),
        url(r'^student_communications/(?P<student_id>\d+)/$', StudentCommunicationView.as_view(), name='student_communications'),

        url(r'^course_page_visits/$', CoursePageVisitsView.as_view(), name='course_page_visits'),
        url(r'^student_page_visits/$', StudentPageVisitsView.as_view(), name='student_page_visits'),

        url(r'^top_assessments/(?:(?P<week_num>\d+)/)?$', TopAssessmentAccessView.as_view(), name='top_assessment'), # optional week
        url(r'^top_communication/(?:(?P<week_num>\d+)/)?$', TopCommunicationAccessView.as_view(), name='top_communication'), # optional week
        url(r'^top_content/(?:(?P<week_num>\d+)/)?$', TopAccessedContentView.as_view(), name='top_content'), # optional week
        url(r'^top_users/$', TopCourseUsersViewSet.as_view(), name='top_users'),

        url(r'^weekly_page_visits/(?P<week_num>\d+)/$', PerWeekPageVisitsView.as_view(), name='per_week_page_visits'),
        url(r'^weekly_metrics/(?P<week_num>\d+)/$', PerWeekMetricsView.as_view(), name='per_week_metrics'),

        url(r'^resource/(?P<resource_id>\d+)/not_viewed_students/$', StudentsNotViewedResourceView.as_view(), name='students_not_viewed_resource'),

    ])),
]

django-root/dashboard/models.py
from datetime import datetime
from datetime import timedelta
import pytz

from authtools.models import User
from django.conf import settings
from django.db import models
from django.utils import timezone
from rest_framework.authtoken.models import Token


class LMSServer(models.Model):
    name = models.CharField(max_length=255)
    descriptions = models.TextField(blank=True)
    token = models.ForeignKey(Token, on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class CourseOffering(models.Model):
    LMS_TYPE_BLACKBOARD = 'blackboard'
    LMS_TYPE_MOODLE = 'moodle'
    LMS_TYPE_CHOICES = (
        (LMS_TYPE_BLACKBOARD, 'Blackboard'),
        (LMS_TYPE_MOODLE, 'Moodle'),
    )

    # Types for Blackboard.  See utils.get_contenttypes for other LMS
    COMMUNICATION_TYPES = (
        'resource/x-bb-discussionboard',
        'course/x-bb-collabsession', # TODO: Check if this is course/ or resource/.
        'resource/x-bb-collabsession', # Include both, can't hurt.
        'resource/x-bb-discussionfolder',
    )
    ASSESSMENT_TYPES = (
        'assessment/x-bb-qti-test',
        'course/x-bb-courseassessment',
        'resource/x-turnitin-assignment',
        # These two are derived from pages in a test import which have submission attempts.
        'resource/x-bb-asmt-survey-link',
        'resource/x-bb-asmt-test-link',
    )

    code = models.CharField(max_length=100)
    title = models.CharField(max_length=255)
    offering = models.CharField(max_length=255)
    owners = models.ManyToManyField(User)
    start_date = models.DateField(help_text='Start date must be on a Monday')
    no_weeks = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    lms_type = models.CharField(max_length=50, choices=LMS_TYPE_CHOICES, default=LMS_TYPE_BLACKBOARD)
    last_activity_at = models.DateTimeField(blank=True, null=True)  # The last recorded page visit, submission attempt or summary post
    is_importing = models.BooleanField(default=False)
    lms_server = models.ForeignKey(LMSServer, null=True, blank=True, help_text='If empty, then this course offering will not be able to be imported')

    class Meta:
        unique_together = ('code', 'lms_server')

    @classmethod
    def assessment_types(cls):
        return cls.ASSESSMENT_TYPES

    @classmethod
    def communication_types(cls):
        return cls.COMMUNICATION_TYPES

    @property
    def end_date(self):
        return self.start_date + timedelta(weeks=self.no_weeks)

    def get_weeks(self):
        start_week = self.start_date.isocalendar()[1]
        end_week = self.end_date.isocalendar()[1]
        return list(range(start_week, end_week))

    @property
    def start_datetime(self):
        local_tz = pytz.timezone(settings.TIME_ZONE)

        return timezone.make_aware(datetime(
            self.start_date.year,
            self.start_date.month,
            self.start_date.day
        ), local_tz)

    @property
    def end_datetime(self):
        local_tz = pytz.timezone(settings.TIME_ZONE)
        end_date = self.end_date

        return timezone.make_aware(datetime(
            end_date.year,
            end_date.month,
            end_date.day
        ), local_tz)

    def get_last_activity_date(self):
        last_activity_at = self.last_activity_at
        if not last_activity_at:
            last_activity_at = self.start_datetime
        return last_activity_at

    def __str__(self):
        return self.code


class CourseSubmissionEvent(models.Model):
    EVENT_TYPE_ASSIGNMENT = 'assignment'
    EVENT_TYPE_QUIZ = 'quiz'
    EVENT_TYPE_CHOICES = (
        (EVENT_TYPE_ASSIGNMENT, 'Assignment'),
        (EVENT_TYPE_QUIZ, 'Quiz'),
    )

    title = models.CharField(max_length=255)
    course_offering = models.ForeignKey(CourseOffering)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    event_type = models.CharField(max_length=50, choices=EVENT_TYPE_CHOICES, default=EVENT_TYPE_ASSIGNMENT)

    def get_event_type(self):
        return dict(self.EVENT_TYPE_CHOICES)[self.event_type]

    def __str__(self):
        return self.title


class CourseSingleEvent(models.Model):
    title = models.CharField(max_length=255)
    course_offering = models.ForeignKey(CourseOffering)
    event_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.title


class CourseRepeatingEvent(models.Model):
    EVENT_DAY_MON = 0
    EVENT_DAY_TUE = 1
    EVENT_DAY_WED = 2
    EVENT_DAY_THU = 3
    EVENT_DAY_FRI = 4
    EVENT_DAY_SAT = 5
    EVENT_DAY_SUN = 6
    EVENT_DAY_CHOICES = (
        (EVENT_DAY_MON, 'Monday'),
        (EVENT_DAY_TUE, 'Tuesday'),
        (EVENT_DAY_WED, 'Wednesday'),
        (EVENT_DAY_THU, 'Thursday'),
        (EVENT_DAY_FRI, 'Friday'),
        (EVENT_DAY_SAT, 'Saturday'),
        (EVENT_DAY_SUN, 'Sunday'),
    )

    title = models.CharField(max_length=255)
    course_offering = models.ForeignKey(CourseOffering)
    start_week = models.IntegerField()
    end_week = models.IntegerField()
    day_of_week = models.IntegerField(choices=EVENT_DAY_CHOICES, default=EVENT_DAY_MON)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_event_day(self):
        return dict(self.EVENT_DAY_CHOICES)[self.day_of_week]

    def __str__(self):
        return self.title


class PedagogyHelper(models.Model):
    pedagogyhelper_json = models.TextField(blank=False)
    course_offering = models.ForeignKey(CourseOffering)

django-root/dashboard/views/assessment.py
from django.views.generic.base import TemplateView
from djangorestframework_camel_case.render import CamelCaseJSONRenderer

from dashboard.models import CourseRepeatingEvent

class CourseAssessmentView(TemplateView):
    template_name = 'dashboard/assessment.html'

    def get(self, request, *args, **kwargs):
        self.course_offering = request.course_offering

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        repeating_events = CourseRepeatingEvent.objects.filter(course_offering=self.course_offering)

        event = repeating_events.first()
        event_id = event.id if event else None

        initial_data = {
            'num_weeks': self.request.course_offering.no_weeks,
            'event_id': event_id,
            'course_id': self.request.course_offering.id,
        }

        context['initial_data'] = CamelCaseJSONRenderer().render(initial_data)
        context['repeating_events'] = repeating_events

        return context

django-root/dashboard/views/communication.py
from django.views.generic.base import TemplateView
from djangorestframework_camel_case.render import CamelCaseJSONRenderer

from dashboard.models import CourseRepeatingEvent

class CourseCommunicationView(TemplateView):
    template_name = 'dashboard/communication.html'

    def get(self, request, *args, **kwargs):
        self.course_offering = request.course_offering

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        repeating_events = CourseRepeatingEvent.objects.filter(course_offering=self.course_offering)

        event = repeating_events.first()
        event_id = event.id if event else None

        initial_data = {
            'num_weeks': self.request.course_offering.no_weeks,
            'event_id': event_id,
            'course_id': self.request.course_offering.id,
        }

        context['initial_data'] = CamelCaseJSONRenderer().render(initial_data)
        context['repeating_events'] = repeating_events

        return context

django-root/dashboard/views/courses.py
from django.views.generic.base import TemplateView

from dashboard.models import CourseOffering


class CourseListView(TemplateView):
    template_name = 'dashboard/course_list.html'

    def get_context_data(self, **kwargs):
        courses = CourseOffering.objects.filter(owners=self.request.user)

        context = super().get_context_data(**kwargs)
        context['courses'] = courses
        return context

django-root/dashboard/templates/dashboard/_course_offering_breadcrumbs.html
<ol class="breadcrumb">
  <li><a href="{% url 'dashboard:course_list' %}"><i class="glyphicon glyphicon-home glyphicon-fw"></i>My Courses</a></li>
  <li><a href="{% url 'dashboard:course_dashboard' course_id=course_offering.id %}">Course: {{ course_offering.code }} - {{ course_offering.title }}</a></li>
  <li class="active">{{ title }}</li>
</ol>

django-root/dashboard/templates/dashboard/course_list.html
{% extends 'base.html' %}

{% block title %}My Courses{% endblock %}

{% block content %}
      <div class="row">
        <div class="col-sm-12">
          <div class="box">
          <div class="box-header" data-original-title>
            <h2><i class="glyphicon glyphicon-user"></i><span class="break"></span>Courses</h2>
          </div>
          <div class="box-content">
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
              <thead>
                <tr>
                  <th>Course Code</th>
                  <th>Course Title</th>
                  <th>Offering</th>
                  <th>LMS</th>
                  <th>Start Date</th>
                  <th>Duration</th>
                  <th>Actions</th>
                  <th>Last Update</th>
                </tr>
              </thead>
              <tbody>
                {% for course in courses %}
                  <tr>
                    <td>{{ course.code }}</td>
                    <td class="center">{{ course.title }}</td>
                    <td class="center">{{ course.offering }}</td>
                    <td class="center">{{ course.lms_type }}</td>
                    <td class="center">{{ course.start_date }}</td>
                    <td class="center">{{ course.no_weeks }} Weeks</td>
                    <td class="center">
                      <a href="{% url 'dashboard:course_dashboard' course_id=course.id %}" class="btn btn-small btn-primary">Learning Analytics Tool</a>
                    </td>
                    <td class="center">TODO</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        </div><!--/col-->

      </div><!--/row-->
{% endblock content %}

django-root/dashboard/templates/dashboard/course_repeating_events_list.html
{% extends 'base.html' %}

{% block title %}Recurring Events{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      {% include "dashboard/_course_offering_breadcrumbs.html" with course_offering=request.course_offering title="Repeating Events" %}
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="box">
      <div class="box-header" data-original-title>
        <h2><i class="glyphicon glyphicon-user glyphicon-fw"></i>Repeating Events for {{ request.course_offering.name }}</h2>
      </div>
      <div class="box-content">
        <p>
          <a href="{% url 'dashboard:add_course_repeating_event' course_id=request.course_offering.id %}" class="btn btn-primary">Add Repeating Event</a>
        </p>
        <table class="table table-striped table-bordered bootstrap-datatable datatable">
          <thead>
            <tr>
              <th>Name</th>
              <th>Day of Week</th>
              <th>Start Week</th>
              <th>End Week</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
              <tr>
                <td>
                  <a href="{% url 'dashboard:edit_course_repeating_event' course_id=request.course_offering.id pk=object.id %}" class="btn btn-link">{{ object.title }}</a>
                </td>
                <td>{{ object.get_event_day }}</td>
                <td class="text-right">{{ object.start_week }}</td>
                <td class="text-right">{{ object.end_week }}</td>
                <td>
                   <a href="{% url 'dashboard:delete_course_repeating_event' course_id=request.course_offering.id pk=object.id %}" class="btn btn-link">Delete</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>

        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
      </div>
    </div>
    </div><!--/col-->
  </div><!--/row-->
{% endblock content %}

django-root/dashboard/templates/dashboard/course_single_events_list.html
{% extends 'base.html' %}

{% block title %}Single Events{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    {% include "dashboard/_course_offering_breadcrumbs.html" with course_offering=request.course_offering title="Single Events" %}
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="box">
      <div class="box-header" data-original-title>
        <h2>
          <i class="glyphicon glyphicon-user glyphicon-fw"></i>
          Single Events for {{ request.course_offering.name }}
        </h2>
      </div>
      <div class="box-content">
        <p>
          <a href="{% url 'dashboard:add_course_single_event' course_id=request.course_offering.id %}"
           class="btn btn-primary">Add Single Event</a>
        </p>
        <table class="table table-striped table-bordered bootstrap-datatable datatable">
          <thead>
          <tr>
            <th>Name</th>
            <th>Event Date</th>
            <th></th>
          </tr>
          </thead>
          <tbody>
          {% for object in object_list %}
          <tr>
            <td>
              <a href="{% url 'dashboard:edit_course_single_event' course_id=request.course_offering.id pk=object.id %}"
                 class="btn btn-link">{{ object.title }}</a>
            </td>
            <td class="text-right">{{ object.event_date|date:datetime_output_format }}</td>
            <td>
              <a
                href="{% url 'dashboard:delete_course_single_event' course_id=request.course_offering.id pk=object.id %}"
                class="btn btn-link">Delete</a>
            </td>
          </tr>
          {% endfor %}
          </tbody>
        </table>

        {% if is_paginated %}
        <ul class="pagination">
          {% if page_obj.has_previous %}
          <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
          {% else %}
          <li class="disabled"><span>&laquo;</span></li>
          {% endif %}
          {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
          <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
          <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
          {% else %}
          <li class="disabled"><span>&raquo;</span></li>
          {% endif %}
        </ul>
        {% endif %}
      </div>
    </div>
  </div><!--/col-->
</div><!--/row-->
{% endblock content %}

django-root/dashboard/templates/dashboard/course_submission_events_list.html
{% extends 'base.html' %}

{% block title %}Submission Events{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      {% include "dashboard/_course_offering_breadcrumbs.html" with course_offering=request.course_offering title="Submission Events" %}
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="box">
      <div class="box-header" data-original-title>
        <h2><i class="glyphicon glyphicon-user glyphicon-fw"></i>Submission Events for {{ request.course_offering.name }}</h2>
      </div>
      <div class="box-content">
        <p>
          <a href="{% url 'dashboard:add_course_submission_event' course_id=request.course_offering.id %}" class="btn btn-primary">Add Submission Event</a>
        </p>
        <table class="table table-striped table-bordered bootstrap-datatable datatable">
          <thead>
            <tr>
              <th>Name</th>
              <th>Start Date</th>
              <th>End Date</th>
              <th>Submission Type</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
              <tr>
                <td>
                  <a href="{% url 'dashboard:edit_course_submission_event' course_id=request.course_offering.id pk=object.id %}" class="btn btn-link">{{ object.title }}</a>
                </td>
                <td class="text-right">{{ object.start_date|date:datetime_output_format }}</td>
                <td class="text-right">{{ object.end_date|date:datetime_output_format }}</td>
                <td>{{ object.get_event_type }}</td>
                <td>
                   <a href="{% url 'dashboard:delete_course_submission_event' course_id=request.course_offering.id pk=object.id %}" class="btn btn-link">Delete</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>

        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
      </div>
    </div>
    </div><!--/col-->
  </div><!--/row-->
{% endblock content %}

django-root/dashboard/templates/dashboard/login.html
{% extends "base_unauthorised.html" %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
      <div class="login-box">
        <h2>Login to your Loop account:</h2>
        <form id="login_form" method="post">
          {% csrf_token %}
          {{ form }}
          <div class="button-login">
            <button type="submit" class="btn btn-primary">Login</button>
          </div>
        </form>
      </div>
    </div><!--/col-->
  </div><!--/.fluid-container-->
</div><!--/fluid-row-->
{% endblock body %}